language: generic
sudo: required
cache:
  timeout: 600
  directories:
  - "$TRAVIS_BUILD_DIR/target/debug"
  - "/opt/.cargo/git"
  - "/opt/.cargo/registry"
  - "./docker/release"
stages:
- Release
- IntegrateTest
before_install:
- docker pull cita/cita-build:ubuntu-18.04-20191128
jobs:
  include:
  - stage: Release
    name: Release for Integrate Test
    language: node_js
    node_js:
    # - lts/*
    - 8.10.0
    cache:
      directories:
      - $TRAVIS_BUILD_DIR/target/release-cache
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_script:
    - cd $TRAVIS_BUILD_DIR
    - ./scripts/replace_default_feature.sh ./ sha3hash  ${HASH_ALGO}
    - ./scripts/replace_default_feature.sh ./ secp256k1 ${CRYPTO_ALGO}
    script: ./env.sh make release
    before_cache:
    - cd $TRAVIS_BUILD_DIR
    - rm -rf target/release-cache
    - mv -vf target/install target/release-cache

  - &stage-contract-test-sha3-secp256k1
    stage: IntegrateTest
    name: Unit Group
    language: node_js
    node_js:
    # - lts/*
    - 8.10.0
    cache:
      directories:
      - $TRAVIS_BUILD_DIR/target/release-cache
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_install:
    - cd $TRAVIS_BUILD_DIR
    - rm -rf target/install
    - cp -rv target/release-cache target/install
    install:
    - rm -rf /opt/cita-run/test-chain
    - cd $TRAVIS_BUILD_DIR/target/install
    - ./bin/cita create
      --nodes "127.0.0.1:4100"
      --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
    - ./bin/cita setup test-chain/0
    - ./bin/cita start test-chain/0
    before_script:
    - cd $TRAVIS_BUILD_DIR/target/install/scripts/contracts/tests
    - travis_retry yarn install
    script: npm run-script unit_group
  - <<: *stage-contract-test-sha3-secp256k1
    name: Integrate AutoExec
    install:
    - cd $TRAVIS_BUILD_DIR/target/install
    - ./bin/cita create
      --nodes "127.0.0.1:4100"
      --contract_arguments "SysConfig.autoExec=true"
      --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
    - ./bin/cita setup test-chain/0
    - ./bin/cita start test-chain/0
    script:
    - npm run-script auto_exec
before_deploy:
- "./scripts/release_multi_algorithm.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TLesx+Pnb6vmCES1u3+Grt/EpCB/yBU+DxC5vd2ET08l+8xc4p34Psf1gi+U+t4gNKDp49Q3N/HHR2Fjl06fvoaI+rt+Cz/Gk3itAr9O2ngA9Zpw67Ut+VmIzTpP0yyjR3EsGUdEnnUNu6a4z2vKOrohXC/6PqoEOzpJUHyDjQGhEv0xBKTezXWX2YtiBVa6QP52t10IXBw9RcxKyXyFz1Htwt4HA7UR0dVVRgVe1DfaK95FZOgDOXGcSbDJOcru5R8b/752elJUUWEiRoBzkWpPp/cuKv2sK350eFfd18t3vwnLRM5BNWtyi7YkYJaXzib1Vj0aH9iEshPenu5ugE1GMGZFss0sZQBw5nC75Qrxiz0OWumgHHuDoZtAbszVujF9Xy9vErMUzmob4b/tCo1qiZ0h1Xe7T8nQeSJKMh295r4NFPAt+U41kOkvEhEZW27bceDRRkI4EHQGfCh378n6geEo74YEGgB0tSESevOtPameJBfoomdD67ORZCUBPQrORGh5MrvcHTf03+i4OIhtJTqlbStXbt7+zvaXQQjfR+1Jodj12rLaDkuUYcUPNOZJk3jWw5LvTNu8V8iYMWD3qXHynqYKctc3vOcbT8hZBbSt0HMuUWF2+wS1ZdAINmESdzQfShAuBtMQNYhAtTruluKeEVhQKjCmb4xSK8s=
  file:
  - "./docker/release/cita_secp256k1_sha3.tar.gz"
  - "./docker/release/cita_sm2_sm3.tar.gz"
  - "./docker/release/cita_ed25519_blake2b.tar.gz"
  on:
    tags: true
