language: generic
sudo: required
cache:
  timeout: 600
  directories:
  - $TRAVIS_BUILD_DIR/target/debug
  - /opt/.cargo/git
  - /opt/.cargo/registry
services:
- docker
git:
  depth: 1
stages:
- CheckShell
- Release
- IntegrateTest
before_install:
- docker pull cita/cita-build:ubuntu-18.04-20191128
jobs:
  include:
  - stage: Release
    name: Release for Integrate Test
    language: node_js
    node_js:
    # - lts/*
    - 8.10.0
    cache:
      directories:
      - $TRAVIS_BUILD_DIR/target/release-cache
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_script:
    - cd $TRAVIS_BUILD_DIR
    - ./scripts/replace_default_feature.sh ./ sha3hash  ${HASH_ALGO}
    - ./scripts/replace_default_feature.sh ./ secp256k1 ${CRYPTO_ALGO}
    script: ./env.sh make release
    before_cache:
    - cd $TRAVIS_BUILD_DIR
    - rm -rf target/release-cache
    - mv -vf target/install target/release-cache

  - &stage-contract-test-sha3-secp256k1
    stage: IntegrateTest
    name: Unit Group
    language: node_js
    node_js:
    # - lts/*
    - 8.10.0
    cache:
      directories:
      - $TRAVIS_BUILD_DIR/target/release-cache
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_install:
    - cd $TRAVIS_BUILD_DIR
    - rm -rf target/install
    - cp -rv target/release-cache target/install
    install:
    - rm -rf /opt/cita-run/test-chain
    - cd $TRAVIS_BUILD_DIR/target/install
    - ./bin/cita create
      --nodes "127.0.0.1:4100"
      --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
    - ./bin/cita setup test-chain/0
    - ./bin/cita start test-chain/0
    before_script:
    - cd $TRAVIS_BUILD_DIR/target/install/scripts/contracts/tests
    - travis_retry yarn install
    script: npm run-script unit_group

before_deploy:
  script: ./scripts/release_sha3_only.sh
deploy:
  provider: releases
  api_key:
    secure: UmH2AT2HhPBL3wkaFa5lCRnK5j1PbqeT7w4LpJ7LqS7/YakpIYlMLmLutEVH2Gu8tvhUHM7Wm2soHMWUgo08L+eN7RPeV6t2r6z/5N9aD4I+l7ki5W6XwwZ5kYcs05xuSFn6cJxyPHR4TeM1aZmJ+/ngKAUhdGr6f16z1XAt4HUvg/HKVOZRukbnHp3pKQeMuXYlMSJBsaAvyY64cwGnKQMngAnZJxEG7s/5LfJb3zrlfxm2gRSnvcvTjdfeYSk4kXaWvWVQXeNIwEjNkKu7/EnoaYr5hmylTGukA8lIMeDdmJClroBZeTESJLSZ0gLNIlX03PyM50IVMayKp16+aAf6IY0/CPFYZSCGtR6MyV4GpQBMHgNkNR+B6TtzR9N7CRoXtoKfK5Gb/sba3Y01koaFRwq6Fu0rjofl+u04R8JEMaBKzY/OgjK2nbhYReU63dRWEesFZOxVYhp9v9/Tv+0ZFluq9Aukn7c4ePs96YBaUgCVbtzCebyNx85t05C0RmXaB/EsX7VwXwoJltE8CGJ9A9ZuBusZsjupFNOxsqzrNzhfkro5BVp7jgBgSn0X9D2dx1PL6xNkMneLz5npyrcbshFXjOkMV9d0w9gMX543tQlfuVIBPmrGGFGqX2cRWADwoRKKfxVSoWrHR0RhQk8dF3pcVsmILS70PCoSqGI=
  file:
  - "./docker/release/cita_secp256k1_sha3.tar.gz"
  on:
    tags: true
