language: generic
sudo: required
cache:
  timeout: 1024
  directories:
  - "./docker/release"
  stages:
  - secp256k1
  - sm2
  - blake2b
  before_install:
  - docker pull cita/cita-build:ubuntu-18.04-20191128
  jobs:
    include:
    - stage: secp256k1
      script:
      - "./scripts/release_sha3.sh"
    - stage: sm2
      script:
      - "./scripts/release_sm2.sh"
    - stage: blake2b
      script:
      - "./scripts/release_black2b.sh"
deploy:
  provider: releases
  api_key:
    secure: UmH2AT2HhPBL3wkaFa5lCRnK5j1PbqeT7w4LpJ7LqS7/YakpIYlMLmLutEVH2Gu8tvhUHM7Wm2soHMWUgo08L+eN7RPeV6t2r6z/5N9aD4I+l7ki5W6XwwZ5kYcs05xuSFn6cJxyPHR4TeM1aZmJ+/ngKAUhdGr6f16z1XAt4HUvg/HKVOZRukbnHp3pKQeMuXYlMSJBsaAvyY64cwGnKQMngAnZJxEG7s/5LfJb3zrlfxm2gRSnvcvTjdfeYSk4kXaWvWVQXeNIwEjNkKu7/EnoaYr5hmylTGukA8lIMeDdmJClroBZeTESJLSZ0gLNIlX03PyM50IVMayKp16+aAf6IY0/CPFYZSCGtR6MyV4GpQBMHgNkNR+B6TtzR9N7CRoXtoKfK5Gb/sba3Y01koaFRwq6Fu0rjofl+u04R8JEMaBKzY/OgjK2nbhYReU63dRWEesFZOxVYhp9v9/Tv+0ZFluq9Aukn7c4ePs96YBaUgCVbtzCebyNx85t05C0RmXaB/EsX7VwXwoJltE8CGJ9A9ZuBusZsjupFNOxsqzrNzhfkro5BVp7jgBgSn0X9D2dx1PL6xNkMneLz5npyrcbshFXjOkMV9d0w9gMX543tQlfuVIBPmrGGFGqX2cRWADwoRKKfxVSoWrHR0RhQk8dF3pcVsmILS70PCoSqGI=
  file:
    - "./docker/release/cita_secp256k1_sha3.tar.gz"
    - "./docker/release/cita_sm2_sm3.tar.gz"
    - "./docker/release/cita_ed25519_blake2b.tar.gz"
  on:
     tags: true
