language: generic
sudo: required
cache:
  timeout: 1024
  directories:
  - ./docker/release
  stages:
  - secp256k1
  - sm2
  - blake2b
  before_install:
  - docker pull cita/cita-build:ubuntu-18.04-20191128
  jobs:
    include:
    - stage: secp256k1
      script:
      # Fail if any of these files have warnings
      - ./scripts/release_sha3.sh
    - stage: sm2
      script:
        # Fail if any of these files have warnings
      -  ./scripts/release_sm2.sh
    - stage: blake2b
      script:
        # Fail if any of these files have warnings
      - ./scripts/release_black2b.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TLesx+Pnb6vmCES1u3+Grt/EpCB/yBU+DxC5vd2ET08l+8xc4p34Psf1gi+U+t4gNKDp49Q3N/HHR2Fjl06fvoaI+rt+Cz/Gk3itAr9O2ngA9Zpw67Ut+VmIzTpP0yyjR3EsGUdEnnUNu6a4z2vKOrohXC/6PqoEOzpJUHyDjQGhEv0xBKTezXWX2YtiBVa6QP52t10IXBw9RcxKyXyFz1Htwt4HA7UR0dVVRgVe1DfaK95FZOgDOXGcSbDJOcru5R8b/752elJUUWEiRoBzkWpPp/cuKv2sK350eFfd18t3vwnLRM5BNWtyi7YkYJaXzib1Vj0aH9iEshPenu5ugE1GMGZFss0sZQBw5nC75Qrxiz0OWumgHHuDoZtAbszVujF9Xy9vErMUzmob4b/tCo1qiZ0h1Xe7T8nQeSJKMh295r4NFPAt+U41kOkvEhEZW27bceDRRkI4EHQGfCh378n6geEo74YEGgB0tSESevOtPameJBfoomdD67ORZCUBPQrORGh5MrvcHTf03+i4OIhtJTqlbStXbt7+zvaXQQjfR+1Jodj12rLaDkuUYcUPNOZJk3jWw5LvTNu8V8iYMWD3qXHynqYKctc3vOcbT8hZBbSt0HMuUWF2+wS1ZdAINmESdzQfShAuBtMQNYhAtTruluKeEVhQKjCmb4xSK8s=
  file:
  - "./docker/release/cita_secp256k1_sha3.tar.gz"
  - "./docker/release/cita_sm2_sm3.tar.gz"
  - "./docker/release/cita_ed25519_blake2b.tar.gz"
  on:
    tags: true
